--- !ruby/object:VR_ENV
backup_path: C:/Users/abernhard
browser: firefox
current_file: C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet/bin/MyClass.rb
font_name: Monospace 10
glade_path: glade-3
height: 746
open_files:
- C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet/bin/MyClass.rb
- C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet/main.rb
- C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet/bin/PassphraseDialog.rb
open_folders:
- C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet
- C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet/bin
- C:/Users/abernhard/Documents/GitHub/briggs-is-cool/ramnet/bin/glade
panel_pos: 423
rdoc_command_line: rdoc -x README
run_command_line: ruby main.rb
tab_spaces: 2
width: 1366
